#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_upload_max_filesize --value=50M
ynh_app_setting_set --key=php_post_max_size --value=50M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="database.php" --destination="$install_dir/content/core/config/database.php"

#=================================================
# INSTALL PHPMYFAQ WITH COMPOSER
#=================================================
ynh_script_progression "Installing $app with Composer..."

ynh_composer_exec install --no-dev

#=================================================
# INSTALL PHPMYFAQ
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
	php$php_version composer.phar install
	ynh_hide_warnings corepack enable && corepack prepare pnpm@latest --activate
    ynh_hide_warnings ynh_exec_as_app pnpm install
    ynh_hide_warnings ynh_exec_as_app pnpm build
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
